### PR TITLE
Updated the python and R scripts

### PR DESCRIPTION
**Pull request by maltelau**
Should be easier to use the python script to run in batch (renamed)
Also included the R scripts I used to plot many runs of many parameters at once

### CODE REVIEW

**Comment by d3v1l401** [comment]
For segmentation reasons increase the memory assigned to JVM 1024 mb instead of 1000 mb

**Comment by maltelau** [comment]
Will 1024 + 512 = 1536 do?
Any way it will depend on the pc and the user will probably have to change it.

**Comment by d3v1l401** [comment]
Yes.

**Comment by d3v1l401** [comment]
Since you are using Python, you can make the memory amount reserved to JVM automatically adjustable:
https://stackoverflow.com/questions/31546309/python-standard-library-to-get-total-memory-size

I believe the half of the total memory size is more than enough, but also depends on the amount of effective usage the whole experiment will take: the console mode uses much more RAM memory, since it runs multiple simulations in different threads that might range from small simulations to quite big ones (and AU might need a dedicated server at a certain point).

**Pull request merged**
